import { useState, useEffect } from "react";
import { X, Copy, RefreshCw, Loader2, Sparkles, Check } from "lucide-react";
import type { Channel } from "../domain/channel";
import {
  generateAutoIdeaAndScripts,
  generateDetailedScripts,
  type AutoGeneratedResult,
  type GenerationResponse
} from "../services/openaiScriptGenerator";

interface AIAutoGenerateModalProps {
  isOpen: boolean;
  channel: Channel | null;
  onClose: () => void;
}

const AIAutoGenerateModal = ({
  isOpen,
  channel,
  onClose
}: AIAutoGenerateModalProps) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AutoGeneratedResult | null>(null);
  const [detailedResult, setDetailedResult] =
    useState<GenerationResponse | null>(null);
  const [copied, setCopied] = useState(false);
  const [copiedScriptIndex, setCopiedScriptIndex] = useState<number | null>(
    null
  );
  const [copiedVideoPrompt, setCopiedVideoPrompt] = useState(false);

  useEffect(() => {
    if (isOpen && channel) {
      setError(null);
      setResult(null);
      setDetailedResult(null);
      void handleGenerate();
    } else {
      setResult(null);
      setDetailedResult(null);
      setError(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, channel?.id]);

  const handleGenerate = async () => {
    if (!channel) {
      return;
    }

    setLoading(true);
    setError(null);
    setResult(null);
    setDetailedResult(null);

    try {
      const mode = channel.generationMode || "script";
      
      if (mode === "prompt") {
        // Используем новую функцию для детальных сценариев
        const generated = await generateDetailedScripts(channel);
        setDetailedResult(generated);
      } else {
        // Старый формат для обратной совместимости
        const generated = await generateAutoIdeaAndScripts(channel);
        setResult(generated);
      }
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Не удалось сгенерировать идею. Попробуйте ещё раз."
      );
    } finally {
      setLoading(false);
    }
  };

  const handleCopyAll = async () => {
    if (detailedResult) {
      // Копирование детальных сценариев
      const textToCopy = detailedResult.scenarios
        .map(
          (scenario) =>
            `${scenario.title} (${scenario.durationSeconds} сек):\n\n${scenario.steps
              .map(
                (step) =>
                  `${step.secondFrom}-${step.secondTo}с: ${step.description}${step.dialog.length > 0 ? `\n${step.dialog.map((d) => `${d.character}: "${d.text}"`).join("\n")}` : ""}`
              )
              .join("\n\n")}`
        )
        .join("\n\n---\n\n");

      try {
        await navigator.clipboard.writeText(textToCopy);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (err) {
        setError("Не удалось скопировать в буфер обмена");
      }
      return;
    }

    if (!result) {
      return;
    }

    const textToCopy = `ИДЕЯ РОЛИКА:\n${result.idea}\n\n${result.scripts
      .map((script, index) => `СЦЕНАРИЙ ${index + 1}:\n${script}`)
      .join("\n\n")}`;

    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      setError("Не удалось скопировать в буфер обмена");
    }
  };

  const handleCopyVideoPrompt = async () => {
    if (!detailedResult?.videoPrompt) {
      return;
    }

    try {
      await navigator.clipboard.writeText(detailedResult.videoPrompt);
      setCopiedVideoPrompt(true);
      setTimeout(() => setCopiedVideoPrompt(false), 2000);
    } catch (err) {
      setError("Не удалось скопировать промпт в буфер обмена");
    }
  };

  const handleCopyScript = async (scriptText: string, index: number) => {
    try {
      await navigator.clipboard.writeText(scriptText);
      setCopiedScriptIndex(index);
      setTimeout(() => setCopiedScriptIndex(null), 2000);
    } catch (err) {
      setError("Не удалось скопировать сценарий в буфер обмена");
    }
  };

  if (!isOpen || !channel) {
    return null;
  }

  const handleBackdropClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (e.target === e.currentTarget && !loading) {
      onClose();
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"
      onClick={handleBackdropClick}
    >
      <div
        className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl border border-white/10 bg-slate-900 text-white shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-slate-900/95 backdrop-blur-sm px-6 py-4">
          <div className="flex items-center gap-3">
            <Sparkles className="h-5 w-5 text-brand-light" />
            <h2 className="text-xl font-semibold">
              Автоидея от ИИ для канала "{channel.name}"
            </h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-2 text-slate-400 transition hover:bg-slate-800 hover:text-white"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          {loading && (
            <div className="flex flex-col items-center justify-center py-16">
              <Loader2 className="h-12 w-12 animate-spin text-brand-light" />
              <p className="mt-4 text-lg text-slate-300">
                ИИ придумывает идею и пишет сценарий...
              </p>
              <p className="mt-2 text-sm text-slate-500">
                Это может занять несколько секунд
              </p>
            </div>
          )}

          {error && (
            <div className="rounded-xl border border-red-500/30 bg-red-900/20 p-6">
              <p className="mb-4 text-red-200">{error}</p>
              <button
                type="button"
                onClick={handleGenerate}
                className="flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-red-700"
              >
                <RefreshCw size={16} />
                Повторить
              </button>
            </div>
          )}

          {/* Старый формат (для обратной совместимости) */}
          {result && !loading && (
            <div className="space-y-6">
              {/* Idea Section */}
              <div className="rounded-xl border border-white/10 bg-slate-800/40 p-6">
                <h3 className="mb-3 flex items-center gap-2 text-lg font-semibold text-brand-light">
                  <Sparkles size={20} />
                  Идея ролика
                </h3>
                <p className="text-slate-200 whitespace-pre-wrap">
                  {result.idea}
                </p>
              </div>

              {/* Scripts Section */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-white">Сценарии:</h3>
                {result.scripts.map((script, index) => (
                  <div
                    key={index}
                    className="relative rounded-xl border border-white/10 bg-slate-800/40 p-6"
                  >
                    <div className="mb-3 flex items-center justify-between gap-2">
                      <span className="rounded-full bg-brand/20 px-3 py-1 text-sm font-semibold text-brand-light">
                        Сценарий {index + 1}
                      </span>
                      <button
                        type="button"
                        onClick={() => handleCopyScript(script, index)}
                        className="flex items-center gap-2 rounded-lg border border-white/10 bg-slate-700/50 px-3 py-1.5 text-xs font-medium text-slate-200 transition hover:border-brand/40 hover:bg-slate-700 hover:text-white"
                        title="Копировать сценарий"
                      >
                        {copiedScriptIndex === index ? (
                          <>
                            <Check size={14} className="text-green-400" />
                            <span className="text-green-400">Скопировано</span>
                          </>
                        ) : (
                          <>
                            <Copy size={14} />
                            <span>Копировать</span>
                          </>
                        )}
                      </button>
                    </div>
                    <p className="text-slate-200 whitespace-pre-wrap">
                      {script}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Новый формат (детальные сценарии) */}
          {detailedResult && !loading && (
            <div className="space-y-6">
              {/* Scripts Section */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-white">Сценарии:</h3>
                {detailedResult.scenarios.map((scenario, scenarioIndex) => {
                  const scenarioText = `${scenario.title} (${scenario.durationSeconds} сек):\n\n${scenario.steps
                    .map(
                      (step) =>
                        `${step.secondFrom}-${step.secondTo}с: ${step.description}${step.dialog.length > 0 ? `\n${step.dialog.map((d) => `${d.character}: "${d.text}"`).join("\n")}` : ""}`
                    )
                    .join("\n\n")}`;

                  return (
                    <div
                      key={scenarioIndex}
                      className="relative rounded-xl border border-white/10 bg-slate-800/40 p-6"
                    >
                      <div className="mb-4 flex items-center justify-between gap-2">
                        <div>
                          <h4 className="text-lg font-semibold text-brand-light">
                            {scenario.title}
                          </h4>
                          <span className="mt-1 inline-block rounded-full bg-brand/20 px-2 py-0.5 text-xs font-semibold text-brand-light">
                            {scenario.durationSeconds} сек
                          </span>
                        </div>
                        <button
                          type="button"
                          onClick={() =>
                            handleCopyScript(scenarioText, scenarioIndex)
                          }
                          className="flex items-center gap-2 rounded-lg border border-white/10 bg-slate-700/50 px-3 py-1.5 text-xs font-medium text-slate-200 transition hover:border-brand/40 hover:bg-slate-700 hover:text-white"
                          title="Копировать сценарий"
                        >
                          {copiedScriptIndex === scenarioIndex ? (
                            <>
                              <Check size={14} className="text-green-400" />
                              <span className="text-green-400">Скопировано</span>
                            </>
                          ) : (
                            <>
                              <Copy size={14} />
                              <span>Копировать</span>
                            </>
                          )}
                        </button>
                      </div>

                      <div className="space-y-3">
                        {scenario.steps.map((step, stepIndex) => (
                          <div
                            key={stepIndex}
                            className="rounded-lg border border-white/5 bg-slate-900/40 p-4"
                          >
                            <div className="mb-2 flex items-center gap-2">
                              <span className="rounded bg-brand/20 px-2 py-1 text-xs font-semibold text-brand-light">
                                {step.secondFrom}-{step.secondTo}с
                              </span>
                            </div>
                            <p className="mb-2 text-sm text-slate-200">
                              {step.description}
                            </p>
                            {step.dialog.length > 0 && (
                              <div className="mt-3 space-y-1 border-t border-white/5 pt-3">
                                {step.dialog.map((line, dialogIndex) => (
                                  <div
                                    key={dialogIndex}
                                    className="text-sm text-slate-300"
                                  >
                                    <span className="font-semibold text-brand-light">
                                      {line.character}:
                                    </span>{" "}
                                    <span className="italic">"{line.text}"</span>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* VIDEO_PROMPT блок (только для режима "prompt") */}
              {detailedResult.videoPrompt && (
                <div className="rounded-xl border border-brand/30 bg-brand/5 p-6">
                  <div className="mb-4 flex items-center justify-between">
                    <h3 className="text-lg font-semibold text-brand-light">
                      🎬 Промпт для генерации видео
                    </h3>
                    <button
                      type="button"
                      onClick={handleCopyVideoPrompt}
                      className="flex items-center gap-2 rounded-lg border border-brand/30 bg-brand/10 px-3 py-1.5 text-xs font-medium text-brand-light transition hover:bg-brand/20"
                    >
                      <Copy size={14} />
                      {copiedVideoPrompt ? "Скопировано!" : "Копировать"}
                    </button>
                  </div>
                  <textarea
                    readOnly
                    value={detailedResult.videoPrompt}
                    rows={12}
                    className="w-full rounded-lg border border-white/10 bg-slate-950/60 px-4 py-3 text-sm text-slate-200 outline-none"
                  />
                  <p className="mt-2 text-xs text-slate-400">
                    Готовый промпт для Sora / Veo 3.1 Fast. Скопируйте и
                    используйте для генерации видео.
                  </p>
                </div>
              )}
            </div>
          )}

          {/* Action Buttons */}
          {(result || detailedResult) && !loading && (
            <div className="mt-6 flex flex-wrap gap-3 border-t border-white/10 pt-6">
              <button
                type="button"
                onClick={handleCopyAll}
                className="flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-semibold text-white transition hover:bg-brand-dark"
              >
                {copied ? (
                  <>
                    <Check size={16} />
                    Скопировано!
                  </>
                ) : (
                  <>
                    <Copy size={16} />
                    Копировать всё
                  </>
                )}
              </button>
              <button
                type="button"
                onClick={handleGenerate}
                disabled={loading}
                className="flex items-center gap-2 rounded-xl border border-white/10 bg-slate-800/60 px-5 py-3 text-sm font-semibold text-slate-200 transition hover:border-brand/40 hover:text-white disabled:cursor-not-allowed disabled:opacity-50"
              >
                <RefreshCw size={16} className={loading ? "animate-spin" : ""} />
                Перегенерировать
              </button>
              <button
                type="button"
                onClick={onClose}
                className="ml-auto rounded-xl border border-white/10 bg-slate-800/60 px-5 py-3 text-sm font-semibold text-slate-200 transition hover:border-brand/40 hover:text-white"
              >
                Закрыть
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AIAutoGenerateModal;

